# Configure main menu and social menu
#[[main]]
#identifier = "home"
#weight = -10
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/lihan3238"

[social.params]
icon = "brand-github"

#[[social]]
#identifier = "twitter"
#name = "Twitter"
#url = "https://twitter.com"

#[social.params]
#icon = "brand-twitter"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:lihan3238@163.com"

[social.params]
icon = "mail"

[[social]]
identifier = "rss"
name = "Rss"
url = "lihan3238.github.io/index.xml"

[social.params]
icon = "rss"
